queue:
  name: Hosted VS2017

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: npm install
  displayName: Install dependencies

- task: RichCodeNavIndexer@0
  inputs:
    languages: typescript
